Update docs for quality metrics
datajoint/element-array-ephys pull request #138
Opened 2023-03-15 17:31 UTC by JaerongA

- Fix some doc errors in the docstring.
- Added docstrings for quality metric tables. 
- Updated `concepts.md`

2023-03-31 17:21 UTC, kabilar requested changes
Thanks @JaerongA.  Please update to include rendering of the quality metrics Jupyter notebook in `workflow-array-ephys` on the docs page (e.g. see https://datajoint.com/docs/elements/element-array-ephys/0.2/tutorials/00-data-download-optional/).

2023-04-10 17:17 UTC, kabilar commented on requirements.txt
> +spikeextractors
```suggestion
```

2023-04-10 17:17 UTC, kabilar commented on requirements.txt
> +spikeextractors
I could be mistaken, but I don't believe that `spikeextractors` is required for this package.

2023-04-10 17:25 UTC, kabilar commented on docs/src/concepts.md
> +| QualityMetricSet | A table to store a set of quality metric values for clusters and its cut-offs. |
```suggestion
| QualityMetricSet | A manual table to match a set of quality metric values for clusters with desired cut-offs. |
```

2023-04-10 17:36 UTC, kabilar commented on element_array_ephys/ephys_report.py
> +        plot_grid (longblob): Figure object.
```suggestion
        plot_grid (longblob): Plotly figure object.
```

2023-04-12 17:48 UTC, JaerongA reviewed
Thanks @kabilar for the feedback. Your suggestions have been committed. I'll add a new figure soon.

2023-04-13 16:04 UTC, kabilar commented on images/attached_array_ephys_element_acute.svg
Please add `SkullReference` to this diagram.

2023-04-13 16:05 UTC, kabilar commented on images/attached_array_ephys_element_chronic.svg
Please add `SkullReference` to this diagram.

2023-04-13 16:07 UTC, kabilar commented on CHANGELOG.md
> ++ Update schema diagrams.
```suggestion

## [0.2.5] - 2023-04-12

+ Add - docstrings for quality metric tables
+ Fix - docstring errors
+ Update - `concepts.md`
+ Update - schema diagrams with quality metrics tables
```

2023-04-13 16:09 UTC, kabilar commented
Thanks for updating the diagrams.  Please add the `SkullRerefence` table to all diagrams.

2023-04-13 16:11 UTC, kabilar commented on CHANGELOG.md
Please add the following to the end of this file:
```
[0.2.5]: https://github.com/datajoint/element-array-ephys/releases/tag/0.2.5
```

2023-04-13 16:55 UTC, kabilar commented
Thanks @JaerongA. Unfortunately, the table name is showing up as it is defined on the database. See image below.

![image](https://user-images.githubusercontent.com/871137/231828373-3373a818-de51-4bb0-8639-b3a038ea8be9.png)

Ideally it should be displayed as `lab.SkullReference`.  Try running `from workflow_array_ephys.pipeline import *` and then displaying the diagram.

2023-04-13 17:13 UTC, JaerongA commented
> Thanks @JaerongA. Unfortunately, the table name is showing up as it is defined on the database. See image below.
> 
> ![image](https://user-images.githubusercontent.com/871137/231828373-3373a818-de51-4bb0-8639-b3a038ea8be9.png)
> 
> Ideally it should be displayed as `lab.SkullReference`. Try running `from workflow_array_ephys.pipeline import *` and then displaying the diagram.

Yeah, I've tried this and that.. and it's still showing it.

2023-04-13 17:28 UTC, JaerongA commented
@kabilar I've updated the diagram, but it's showing as `SkullReference`, not `lab.SkullReference`.

2023-04-13 19:22 UTC, merged