Code cleanup/optimization, variables renaming for clarity
datajoint/element-array-ephys pull request #19
Opened 2021-04-08 21:46 UTC by ttngu207

2021-04-12 19:27 UTC, shenshan approved these changes

2021-04-19 19:27 UTC, dimitri-yatsenko requested changes

2021-04-19 19:27 UTC, dimitri-yatsenko commented on element_array_ephys/__init__.py
> +
```suggestion
        if path.exists() or (root_dir / path).exists():
            return path if root_dir in set(path.parents) else root_dir / path, root_dir
```

2021-04-19 19:27 UTC, dimitri-yatsenko commented on element_array_ephys/readers/kilosort.py
> +                pass
```suggestion
            try:
                cluster_file = next(self._ks_dir.glob(cluster_pattern))
            except StopIteration:
                pass
            cluster_file_suffix = cluster_file.suffix
            assert cluster_file_suffix in ('.csv', '.tsv', '.xlsx')
            break

```

2021-04-19 19:27 UTC, dimitri-yatsenko commented on element_array_ephys/readers/kilosort.py
> +        max_channel_idx = np.abs(np.abs(channel_templates).max(axis=0)).argmax()
```suggestion
        max_channel_idx = np.abs(channel_templates).max(axis=0).argmax()
```

2021-04-20 18:44 UTC, dimitri-yatsenko commented on element_array_ephys/readers/kilosort.py
> +                assert cluster_file_suffix in ('.csv', '.tsv', '.xlsx')
Add message to assert. Or raise a specific error

2021-04-20 18:55 UTC, dimitri-yatsenko approved these changes

2021-04-20 18:55 UTC, merged