Update to permit multiple root dirs
datajoint/element-array-ephys pull request #41
Opened 2021-11-12 23:08 UTC by CBroz1

Within `ephys.py`, multiple instances of grabbing the full session path with `find_full_path` from the element's `__init__.py`. See [parallel PR]() for `workflow-array-ephys`

2021-11-26 18:15 UTC, dimitri-yatsenko approved these changes

2021-12-29 21:39 UTC, kabilar requested changes
Thanks @CBroz1.  Good catch.  Lets use `find_full_path` from `element-data-loader.utils`.  In this pull request, could you please also set up the `ephys` module to use `dict_to_uuid` and `find_root_directory` from `element-data-loader.utils`?  And then we can remove these functions from the `__init__.py`.

2021-12-29 21:43 UTC, kabilar commented
I just actually realized that my suggested changes are in pull request #35.  Could you please review this pull request first?

2021-12-30 00:52 UTC, CBroz1 commented
> I just actually realized that my suggested changes are in pull request #35
Unfortunately, I wasn't aware of this PR when you and I discussed me taking on this multiple root task. The changes there are more comprehensive and cover all features present here.

2021-12-30 00:52 UTC, closed without merging