Add `ephys_precluster` module
datajoint/element-array-ephys pull request #65
Opened 2022-04-20 18:45 UTC by kabilar

- Added tables for running multiple pre-clustering analysis steps on the acquired data.
- First I created a copy of `ephys_acute` and then added the additional tables.  See [this commit](https://github.com/datajoint/element-array-ephys/commit/c7a155a9d4ab384d667046fefb316df7d00ed656) for a diff between the `ephys_acute` and `ephys_precluster` modules.
- The `PreClusterParamList` table allows for keeping track of multiple pre-clustering steps and their order of operations.
- The current implementation loads the pre-clustered data.  Future work will focus on triggering the pre-clustering steps.
- I have tested that data populates through this schema correctly.  Once we agree upon the design, I will add pytests to `workflow-array-ephys`.

![precluster_tables](https://user-images.githubusercontent.com/871137/164300244-1bb57d99-7e15-40ce-889e-e578c22f34ad.png)

2022-04-20 18:46 UTC, kabilar commented
@Alvalunasan

2022-04-20 19:07 UTC, kabilar commented
Hi @Alvalunasan, I couldn't add you as a reviewer but please feel free to add any feedback.  Thanks.

2022-04-20 22:09 UTC, kabilar commented
Noticed an issue with the implementation.  Will address and then mark this pull request as `Ready for review`.

2022-04-21 16:20 UTC, kabilar commented
Hi @ttngu207, I have fixed the issue that I noted above in this [commit](https://github.com/datajoint/element-array-ephys/pull/65/commits/3d8ec16a85507d4708ceedfdcffd4609546dc0f7).

2022-04-21 17:26 UTC, kabilar commented
Hi @sidhulyalkar, as you are learning more about `element-array-ephys`.  Feel free to review this pull request.  Thanks.

2022-05-26 15:23 UTC, kabilar commented on element_array_ephys/ephys_precluster.py
> +        -> [nullable] PreClusterParamSet    # Nullable for when pre-clustering is not performed.
```suggestion
        -> PreClusterParamSet
```

2022-05-26 15:23 UTC, kabilar commented on element_array_ephys/ephys_precluster.py
> +    # Ordered list of paramset_idx that are to be run
```suggestion
    # Ordered list of paramset_idx that are to be run
    #  When pre-clustering is not performed, do not create an entry in `ParamOrder`
```

2022-05-26 15:26 UTC, kabilar commented on element_array_ephys/ephys_precluster.py
> +    class ParamOrder(dj.Part):
```suggestion
    class Step(dj.Part):
```

2022-05-26 15:27 UTC, kabilar commented on element_array_ephys/ephys_precluster.py
> +        order_id: smallint                  # Order of operations
```suggestion
        order: smallint                  # Order of operations
```

2022-05-26 15:30 UTC, kabilar commented on element_array_ephys/ephys_precluster.py
> +            creation_time = (EphysRecording & key).fetch1('recording_datetime')
Throw an error if `task_mode=none` and there are entries in `PreClusterParamStep.Step`.

2022-05-26 19:02 UTC, kabilar commented on element_array_ephys/ephys_precluster.py
> +            creation_time = (EphysRecording & key).fetch1('recording_datetime')
Added `ValueError`.

2022-05-26 19:28 UTC, kabilar commented
Hi @ttngu207, I have implemented the changes we discussed and updated the first comment to reflect all changes.  This pull request is ready for review.  Thanks!

2022-05-26 19:55 UTC, dimitri-yatsenko commented on element_array_ephys/ephys_precluster.py
> +            cls.insert1(param_dict)
```suggestion
        cls.insert1(param_dict)
```

You do not need to explicitly handle the duplication errors. DataJoint will already throw a reasonable exception.

2022-05-26 19:58 UTC, dimitri-yatsenko commented on element_array_ephys/ephys_precluster.py
> +                                                 ['SpikeGLX', 'Open Ephys']):
```suggestion
        for ephys_pattern, ephys_acq_type in (('*.ap.meta', 'SpikeGLX'), ('*.oebin',  'Open Ephys')):
```

2022-05-26 20:00 UTC, dimitri-yatsenko commented on element_array_ephys/ephys_precluster.py
> +            cls.insert1(param_dict)
If the datajoint exception is not clear enough, we can work to improve it.

2022-05-26 20:04 UTC, dimitri-yatsenko commented on element_array_ephys/ephys_precluster.py
> +            cls.insert1(param_dict)
```suggestion
        cls.insert1(param_dict)
```

DataJoint already handles these duplication errors better than this code.

2022-05-26 20:08 UTC, dimitri-yatsenko requested changes

2022-05-26 20:08 UTC, dimitri-yatsenko commented on element_array_ephys/ephys_precluster.py
> +                             f' for: {key}; do `Clustering.populate(key)`')
This is a foreign key check.  Database already does this better than this code.
```suggestion
```

2022-05-26 20:08 UTC, dimitri-yatsenko commented on element_array_ephys/ephys_precluster.py
> +                    'spike_depths': spike_depths[kilosort_dataset.data['spike_clusters'] == unit]})
```suggestion
        for unit, unit_label in zip(valid_units, valid_unit_labels):
            if (kilosort_dataset.data['spike_clusters'] == unit).any():
                unit_channel, _ = kilosort_dataset.get_best_channel(unit)
                unit_spike_times = (spike_times[kilosort_dataset.data['spike_clusters'] == unit]
                                    / kilosort_dataset.data['params']['sample_rate'])
                spike_count = len(unit_spike_times)

                units.append({
                    'unit': unit,
                    'cluster_quality_label': unit_label,
                    **channel2electrodes[unit_channel],
                    'spike_times': unit_spike_times,
                    'spike_count': spike_count,
                    'spike_sites': spike_sites[kilosort_dataset.data['spike_clusters'] == unit],
                    'spike_depths': spike_depths[kilosort_dataset.data['spike_clusters'] == unit]})
```

2022-05-26 20:09 UTC, dimitri-yatsenko commented on element_array_ephys/ephys_precluster.py
> +        param_query = cls & {'param_set_hash': param_dict['param_set_hash']}
This `param_query` is unnecessary

2022-05-26 20:22 UTC, dimitri-yatsenko requested changes

2022-05-26 20:22 UTC, dimitri-yatsenko commented on element_array_ephys/ephys_precluster.py
> +                len(oe_probe.lfp_meta['channels_ids']))[-1::-self._skip_channel_counts]
```suggestion
            lfp_channel_ind = slice(len(oe_probe.lfp_meta['channels_ids']))-1, 0, -self._skip_channel_counts)
```

2022-05-26 20:22 UTC, dimitri-yatsenko commented on element_array_ephys/ephys_precluster.py
> +            for channel_idx in np.array(oe_probe.lfp_meta['channels_ids'])[lfp_channel_ind]:
```suggestion
            for channel_idx in oe_probe.lfp_meta['channels_ids'][lfp_channel_ind]:
```

2022-05-26 20:22 UTC, dimitri-yatsenko commented on element_array_ephys/ephys_precluster.py
> +            self.Electrode.insert1({**key, **electrode_key, 'lfp': lfp_trace})
```suggestion
        self.Electrode.insert(dict(key, lfp=lfp_trace, **electrode_key) 
                    for electrode_key, lfp_trace in zip(electrode_keys, lfp))
```

2022-05-27 18:30 UTC, kabilar commented
Thanks @dimitri-yatsenko!  To expedite this merge and since this pull request is focused on adding the `PreCluster` tables, I will create GitHub issues to address your comments in a future pull request.  Your suggestions will have to be replicated across `ephys_acute`, `ephys_chronic`, `ephys_precluster`, and `ephys_no_curation`.

2022-05-27 18:41 UTC, ttngu207 approved these changes
Perhaps add a bit of context/story - e.g. this version of the element-array-ephys is being deployed and used by the Princeton U19 program

2022-05-27 20:33 UTC, dimitri-yatsenko approved these changes

2022-05-27 20:33 UTC, merged

2022-05-27 20:34 UTC, dimitri-yatsenko commented
@kabilar No need for issues. I will issue a PR with these changes.